# Generated by Django 5.1 on 2025-01-14 07:48

import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='uploads/', validators=[videos.models.validate_video_file]),
        ),
    ]
