<<<<<<< HEAD
# Generated by Django 5.1.4 on 2025-01-31 08:04
=======
# Generated by Django 5.1.4 on 2025-01-23 09:54
>>>>>>> 6f56bba57f11ffaf9c3a64ba514f78ff2f77855d

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('videos', '0004_alter_video_channel'),
=======
        ("videos", "0004_alter_video_channel"),
>>>>>>> 6f56bba57f11ffaf9c3a64ba514f78ff2f77855d
    ]

    operations = [
        migrations.RemoveField(
<<<<<<< HEAD
            model_name='video',
            name='tags',
=======
            model_name="video",
            name="tags",
>>>>>>> 6f56bba57f11ffaf9c3a64ba514f78ff2f77855d
        ),
    ]
